# File: main.py

import os
from src.config import API_KEY
from src.data_ingestion import get_ticker_from_name, get_peers_automatically, get_current_market_data, \
    get_historical_fundamentals
from src.analytics import run_relative_valuation
from src.report_generator import generate_agent_prompt, generate_memo_with_llm

if __name__ == "__main__":
    print("=" * 60)
    print("🤖 AI FUNDAMENTAL ANALYST AGENT (MODULAR)")
    print("Pipeline: Ingestion -> Analytics -> Reasoning -> Reporting")
    print("=" * 60)

    # 1. Check API Key
    if not API_KEY:
        print("\n[!] WARNING: No API Key found in 'src/config.py'.")
        print("Please open 'src/config.py' and insert your OpenAI API Key to proceed.")
        exit()

    # 2. User Input
    user_input = input("\nEnter Company Name or Ticker (e.g., 'Starbucks'): ").strip()

    if user_input:
        # 3. Identify Ticker
        print(f"\n[Data Module] Identifying ticker symbol for '{user_input}'...")
        target_ticker = get_ticker_from_name(user_input)

        if target_ticker == "NOT_FOUND" or target_ticker == "ERROR":
            print("Error: Could not identify a valid US stock ticker.")
        else:
            print(f"[Data Module] Target Identified: {target_ticker}")

            # 4. Identify Peers
            print(f"[Data Module] Auto-detecting peer group...")
            peers = get_peers_automatically(target_ticker)
            competitors = [target_ticker] + peers
            print(f"[Data Module] Competitors: {peers}")

            # 5. Fetch Data
            print(f"[Data Module] Fetching Market & Financial Data from Yahoo Finance...")
            df_market = get_current_market_data(competitors)
            df_history = get_historical_fundamentals(target_ticker)

            if df_history.empty or df_market.empty:
                print("Error: Data ingestion failed (Network error or invalid ticker).")
            else:
                # 6. Run Analytics
                print("[Analytics Module] Computing Relative Valuation Multiples...")
                valuation_res, df_final = run_relative_valuation(df_market, target_ticker)

                # 7. Generate Report
                print("[Report Module] Synthesizing Investment Memo via OpenAI...")
                final_prompt = generate_agent_prompt(target_ticker, valuation_res, df_history, df_final)
                memo = generate_memo_with_llm(final_prompt)

                # 8. Save Outputs (Format: Markdown)
                output_file = f"{target_ticker}_Investment_Memo.md"

                with open(output_file, "w", encoding='utf-8') as f:
                    # Write the Investment Memo generated by LLM (now in Markdown)
                    f.write(memo)

                    # Append Audit Trail with Markdown formatting
                    f.write("\n\n---\n")
                    f.write("## APPENDIX: QUANTITATIVE DATA TABLES (AUDIT TRAIL)\n\n")

                    # Use Code Blocks to preserve table alignment
                    f.write("### Table 1: Relative Valuation Data\n")
                    f.write("```text\n")
                    f.write(df_final.to_string())
                    f.write("\n```\n\n")

                    f.write("### Table 2: 5-Year Historical Fundamentals\n")
                    f.write("```text\n")
                    f.write(df_history.to_string())
                    f.write("\n```\n")

                print("\n" + "=" * 50)
                print(f"✅ SUCCESS! Report saved to: {output_file}")

                print("=" * 50)
