import pandas as pd
import numpy as np

def add_indicators(df, cfg):
    """
    Computes technical indicators and appends them to the DataFrame.
    """
    df = df.copy()

    # --- 1. Exponential Moving Averages (EMA) ---
    # Used for trend direction identification
    df['EMA_Short'] = df['Close'].ewm(span=cfg.EMA_SHORT, adjust=False).mean()
    df['EMA_Long'] = df['Close'].ewm(span=cfg.EMA_LONG, adjust=False).mean()

    # --- 2. MACD (Moving Average Convergence Divergence) ---
    # Used for momentum confirmation
    ema_fast = df['Close'].ewm(span=cfg.MACD_FAST, adjust=False).mean()
    ema_slow = df['Close'].ewm(span=cfg.MACD_SLOW, adjust=False).mean()
    df['MACD_Line'] = ema_fast - ema_slow
    df['Signal_Line'] = df['MACD_Line'].ewm(span=cfg.MACD_SIGNAL, adjust=False).mean()

    # --- 3. RSI (Relative Strength Index) ---
    # Used to identify overbought/oversold conditions
    delta = df['Close'].diff()
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    
    # Wilder's Smoothing for RSI
    avg_gain = gain.ewm(alpha=1/cfg.RSI_PERIOD, min_periods=cfg.RSI_PERIOD, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1/cfg.RSI_PERIOD, min_periods=cfg.RSI_PERIOD, adjust=False).mean()

    rs = avg_gain / avg_loss.replace(0, 0.000001)
    df['RSI'] = 100 - (100 / (1 + rs))

    # --- 4. ATR (Average True Range) ---
    # Used for volatility measurement
    high_low = df['High'] - df['Low']
    high_close = np.abs(df['High'] - df['Close'].shift())
    low_close = np.abs(df['Low'] - df['Close'].shift())
    
    ranges = pd.concat([high_low, high_close, low_close], axis=1)
    true_range = ranges.max(axis=1)
    df['ATR'] = true_range.rolling(window=cfg.ATR_PERIOD).mean()

    # Clean up NaN values generated by indicator windows
    df.dropna(inplace=True)
    return df